-- MySQL Script generated by MySQL Workbench
-- 03/25/16 17:18:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema elDesvanDeMika
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `elDesvanDeMika` ;

-- -----------------------------------------------------
-- Schema elDesvanDeMika
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elDesvanDeMika` DEFAULT CHARACTER SET utf8 ;
USE `elDesvanDeMika` ;

-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `whatsup` TINYINT(1) NULL DEFAULT 1,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCLIENTE`),
  UNIQUE INDEX `idCLIENTE_UNIQUE` (`idCLIENTE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`PEDIDO` (
  `Npedido` INT NOT NULL,
  `Fecha_Pedido` DATE NOT NULL,
  `fecha_entrega` DATE NULL,
  `Precio` DECIMAL(4,2) NOT NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`Npedido`),
  UNIQUE INDEX `N pedido_UNIQUE` (`Npedido` ASC),
  INDEX `fk_PEDIDO_CLIENTE_idx` (`CLIENTE_idCLIENTE` ASC),
  CONSTRAINT `fk_PEDIDO_CLIENTE`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `elDesvanDeMika`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`MANUALIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`MANUALIDAD` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`MANUALIDAD` (
  `codManualidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Tiempo` SMALLINT(6) NULL,
  `Foto` LONGBLOB NULL,
  `Observaciones` VARCHAR(75) NULL,
  PRIMARY KEY (`codManualidad`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`COMPONENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`COMPONENTE` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`COMPONENTE` (
  `codComponente` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `precio_unidad` DECIMAL(4,2) NULL,
  PRIMARY KEY (`codComponente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`PROVEEDOR` (
  `Nombre` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `Persona_Contacto` VARCHAR(30) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`COLOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`COLOR` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`COLOR` (
  `idCOLOR` INT NOT NULL AUTO_INCREMENT,
  `Colorprincipal` VARCHAR(15) NOT NULL,
  `Subcolor` VARCHAR(45) NULL,
  PRIMARY KEY (`idCOLOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`MATERIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`MATERIAL` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`MATERIAL` (
  `codMaterial` INT NOT NULL AUTO_INCREMENT,
  `PROVEEDOR_Nombre` VARCHAR(20) NOT NULL,
  `COLOR_idCOLOR` INT NOT NULL,
  `PrecioCoste` DECIMAL(4,2) NULL,
  `cantidad` TINYINT(4) NULL,
  INDEX `fk_MATERIAL_PROVEEDOR1_idx` (`PROVEEDOR_Nombre` ASC),
  PRIMARY KEY (`codMaterial`),
  INDEX `fk_MATERIAL_COLOR1_idx` (`COLOR_idCOLOR` ASC),
  CONSTRAINT `fk_MATERIAL_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_Nombre`)
    REFERENCES `elDesvanDeMika`.`PROVEEDOR` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIAL_COLOR1`
    FOREIGN KEY (`COLOR_idCOLOR`)
    REFERENCES `elDesvanDeMika`.`COLOR` (`idCOLOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`TELA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`TELA` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`TELA` (
  `MATERIAL_codMaterial` INT NOT NULL AUTO_INCREMENT,
  `Estampado` VARCHAR(15) NULL,
  `Tejido` VARCHAR(15) NULL,
  `SegundoColor` INT NOT NULL,
  PRIMARY KEY (`MATERIAL_codMaterial`),
  INDEX `fk_TELA_COLOR1_idx` (`SegundoColor` ASC),
  CONSTRAINT `fk_TELA_MATERIAL1`
    FOREIGN KEY (`MATERIAL_codMaterial`)
    REFERENCES `elDesvanDeMika`.`MATERIAL` (`codMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TELA_COLOR1`
    FOREIGN KEY (`SegundoColor`)
    REFERENCES `elDesvanDeMika`.`COLOR` (`idCOLOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`FIELTRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`FIELTRO` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`FIELTRO` (
  `Grosor` INT NOT NULL,
  `MATERIAL_codMaterial` INT NOT NULL,
  PRIMARY KEY (`MATERIAL_codMaterial`),
  CONSTRAINT `fk_FIELTRO_MATERIAL1`
    FOREIGN KEY (`MATERIAL_codMaterial`)
    REFERENCES `elDesvanDeMika`.`MATERIAL` (`codMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`Arcilla Polimérica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`Arcilla Polimérica` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`Arcilla Polimérica` (
  `Cocida` TINYINT(1) NOT NULL,
  `MATERIAL_codMaterial` INT NOT NULL,
  PRIMARY KEY (`MATERIAL_codMaterial`),
  CONSTRAINT `fk_Arcilla Polimérica_MATERIAL1`
    FOREIGN KEY (`MATERIAL_codMaterial`)
    REFERENCES `elDesvanDeMika`.`MATERIAL` (`codMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`Utileria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`Utileria` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`Utileria` (
  `clase` VARCHAR(15) NOT NULL,
  `MATERIAL_codMaterial` INT NOT NULL,
  PRIMARY KEY (`MATERIAL_codMaterial`),
  CONSTRAINT `fk_Utileria_MATERIAL1`
    FOREIGN KEY (`MATERIAL_codMaterial`)
    REFERENCES `elDesvanDeMika`.`MATERIAL` (`codMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`Abalorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`Abalorio` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`Abalorio` (
  `Hecho_de` VARCHAR(15) NOT NULL,
  `tamaño` VARCHAR(15) NOT NULL,
  `Forma` VARCHAR(15) NOT NULL,
  `MATERIAL_codMaterial` INT NOT NULL,
  PRIMARY KEY (`MATERIAL_codMaterial`),
  CONSTRAINT `fk_Abalorio_MATERIAL1`
    FOREIGN KEY (`MATERIAL_codMaterial`)
    REFERENCES `elDesvanDeMika`.`MATERIAL` (`codMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`LINEASPEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`LINEASPEDIDO` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`LINEASPEDIDO` (
  `PEDIDO_Npedido` INT NOT NULL,
  `MANUALIDAD_codManualidad` INT NOT NULL,
  `cantidad` TINYINT(4) NULL,
  PRIMARY KEY (`PEDIDO_Npedido`, `MANUALIDAD_codManualidad`),
  INDEX `fk_PEDIDO_has_MANUALIDAD_MANUALIDAD1_idx` (`MANUALIDAD_codManualidad` ASC),
  INDEX `fk_PEDIDO_has_MANUALIDAD_PEDIDO1_idx` (`PEDIDO_Npedido` ASC),
  CONSTRAINT `fk_PEDIDO_has_MANUALIDAD_PEDIDO1`
    FOREIGN KEY (`PEDIDO_Npedido`)
    REFERENCES `elDesvanDeMika`.`PEDIDO` (`Npedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_MANUALIDAD_MANUALIDAD1`
    FOREIGN KEY (`MANUALIDAD_codManualidad`)
    REFERENCES `elDesvanDeMika`.`MANUALIDAD` (`codManualidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`SECOMPONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`SECOMPONE` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`SECOMPONE` (
  `MANUALIDAD_codManualidad` INT NOT NULL,
  `COMPONENTE_codComponente` TINYINT(4) NOT NULL,
  `cantidad` TINYINT(4) NOT NULL,
  PRIMARY KEY (`MANUALIDAD_codManualidad`, `COMPONENTE_codComponente`),
  INDEX `fk_COMPONENTE_has_MANUALIDAD1_MANUALIDAD1_idx` (`MANUALIDAD_codManualidad` ASC),
  INDEX `fk_COMPONENTE_has_MANUALIDAD1_COMPONENTE1_idx` (`COMPONENTE_codComponente` ASC),
  CONSTRAINT `fk_COMPONENTE_has_MANUALIDAD1_COMPONENTE1`
    FOREIGN KEY (`COMPONENTE_codComponente`)
    REFERENCES `elDesvanDeMika`.`COMPONENTE` (`codComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPONENTE_has_MANUALIDAD1_MANUALIDAD1`
    FOREIGN KEY (`MANUALIDAD_codManualidad`)
    REFERENCES `elDesvanDeMika`.`MANUALIDAD` (`codManualidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elDesvanDeMika`.`FORMADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elDesvanDeMika`.`FORMADO` ;

CREATE TABLE IF NOT EXISTS `elDesvanDeMika`.`FORMADO` (
  `COMPONENTE_codComponente` TINYINT(4) NOT NULL,
  `MATERIAL_codMaterial` INT NOT NULL,
  `cantidad` TINYINT(4) NULL,
  PRIMARY KEY (`COMPONENTE_codComponente`, `MATERIAL_codMaterial`),
  INDEX `fk_COMPONENTE_has_MATERIAL_MATERIAL1_idx` (`MATERIAL_codMaterial` ASC),
  INDEX `fk_COMPONENTE_has_MATERIAL_COMPONENTE1_idx` (`COMPONENTE_codComponente` ASC),
  CONSTRAINT `fk_COMPONENTE_has_MATERIAL_COMPONENTE1`
    FOREIGN KEY (`COMPONENTE_codComponente`)
    REFERENCES `elDesvanDeMika`.`COMPONENTE` (`codComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPONENTE_has_MATERIAL_MATERIAL1`
    FOREIGN KEY (`MATERIAL_codMaterial`)
    REFERENCES `elDesvanDeMika`.`MATERIAL` (`codMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO desvan;
 DROP USER desvan;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'desvan' IDENTIFIED BY 'mika';

GRANT ALL ON `elDesvanDeMika`.* TO 'desvan';
GRANT SELECT ON TABLE `elDesvanDeMika`.* TO 'desvan';
GRANT SELECT, INSERT, TRIGGER ON TABLE `elDesvanDeMika`.* TO 'desvan';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `elDesvanDeMika`.* TO 'desvan';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
